TRUNCATE TABLE GOLFHOLERECORD;
DELETE FROM GOLFCOURSEDATA;
DELETE FROM GOLFCOURSE ;

ALTER TABLE golfcourse ALTER COLUMN courseId restart with 1;
ALTER TABLE golfcoursedata ALTER COLUMN courseDataId restart with 1;
ALTER TABLE golfholerecord ALTER COLUMN id restart with 1;

insert into GOLFCOURSE (name, address, phone) values ('Beacon Park', 'Some where', '01999 999 999');
insert into GOLFCOURSE (name, address, phone) values ('Bentham', 'Some where else ', '01888 888 888 ');

insert into GOLFCOURSEDATA (courseId, teeColour) values ( 1, 'Yellow');
insert into GOLFCOURSEDATA (courseId, teeColour) values ( 1, 'White');
insert into GOLFCOURSEDATA (courseId, teeColour) values ( 2, 'Yellow');
insert into GOLFCOURSEDATA (courseId, teeColour) values ( 2, 'White');

insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,1,1,468,4,1);
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,1,2,466,4,2);
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,1,3,464,4,3);
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,1,4,368,4,4);
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,1,5,338,4,5);
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,2,1,468,4,1);
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,2,2,466,4,2);
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,2,3,464,4,3);
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,2,4,368,4,4);
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (1,2,5,338,4,5);

insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (2,3,1,468,4,1);
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (2,3,2,466,4,2);
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (2,3,3,464,4,3);
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (2,3,4,368,4,4);
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (2,3,5,338,4,5);
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (2,4,1,468,4,1);
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (2,4,2,466,4,2);
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (2,4,3,464,4,3);
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (2,4,4,368,4,4);
insert into GOLFHOLERECORD (COURSEID, COURSEDATAID, HOLENUMBER, HOLEYARDAGE, HOLEPAR, HOLESI) values (2,4,5,338,4,5);
